services:
  - type: web
    name: fichas-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: FRONTEND_URLS
        value: http://localhost:3000,https://fichas-frontend.onrender.com
      - key: FALLBACK_AUTH
        value: true

  - type: web
    name: fichas-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
      - key: REACT_APP_API_BASE_URL
        value: https://fichas-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html